### ISSUE TITLE
Custom pages

### ISSUE THREAD

**Issue by NikLegaloff** [NikLegaloff/YAShop#1]
1. Добавить новую сущность CustomPage - странички для интернет магазина состоящие из заголовка, самого текста, порядкового номера и алиаса(короткого имени, например delivery) 
2. Сделать 3 страницы с алиасами delivery, payment, returns (создать 3 экземпляра и сохранить в консоли)
3. Добавить просмотр страниц по ссылке /CustomPage/View/?alias=delivery
4. Добавить в меню ссылки на эти страницы.

**Comment by Kattherinee** [comment]
implemented
